### ISSUE TITLE
Tests files naming convention

### ISSUE THREAD

**Issue by gmsantos** [leroy-merlin-br/php-coding-standard#15]
Tests files does not has a naming convention:

![image](https://user-images.githubusercontent.com/1991286/50647348-7c1b8980-0f5f-11e9-9d11-31b38e836729.png)

What should be the convection to use (saving special cases)?

**Comment by gmsantos** [comment]
CamelCase

**Comment by gmsantos** [comment]
snake_case

**Comment by gmsantos** [comment]
[kebab-case](https://en.wikipedia.org/wiki/Letter_case#Special_case_styles)

**Comment by carusogabriel** [comment]
The reason why we have such names is to test the PSR-4 rule. We can keep only one file wrong to test it, if is the case.
