### ISSUE TITLE
Allow @testWith annotation.

### ISSUE THREAD

**Issue by ravanscafi** [leroy-merlin-br/php-coding-standard#25]
It's an alternative to `@dataProvider`.

https://phpunit.de/manual/6.5/en/appendixes.annotations.html#appendixes.annotations.testWith

**Comment by carusogabriel** [comment]
👎 in this one. With Data Providers, we can have more controls of what we are passing to the test, types, return types, call functions, etc.

**Comment by gmsantos** [comment]
I agree that with Data Providers we have more control, but we are not **changing everything**.

In some cases `@testWith` could be handy. Do you have an use case @ravanscafi ?

**Comment by ravanscafi** [comment]
Yeah, I'm using it right now to make some integration tests WAY more clearer than with data providers.

![image](https://user-images.githubusercontent.com/6104262/54056501-02a64e80-41cf-11e9-9c9d-505b801391ec.png)

**Comment by carusogabriel** [comment]
@ravanscafi Have you tried [`yield`](http://php.net/manual/en/language.generators.syntax.php) instead of arrays? It makes things clear as well.

**Comment by ravanscafi** [comment]
Sorry, I can't see an use here. Can you give me an example?

**Comment by gmsantos** [comment]
@carusogabriel even with yield the "data" part of the provider isn't near the test definition, it's in another method. For simple data providers like the example, I agree that it's more simple too.

For complex structures or data providers that is used more than once, I agree that a separate method is better for  legibility of each case and reuse in other tests.

**Comment by carusogabriel** [comment]
Gotcha. So, let's move on with this proposal. 

@ravanscafi Can you make the PR?

**Comment by gmsantos** [comment]
#26

**Comment by ravanscafi** [comment]
See #26
